version: '3.8'

services:
  apigateway:
    container_name: apigateway
    build: .
    ports:
      - "9996:9996"
    networks:
     - renthub
    depends_on:
      minio:
        condition: service_healthy

  minio:
    container_name: minio
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=photos
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://minio:9000/minio/health/live || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - renthub

networks:
  renthub:
    external: true

volumes:
  db:
  minio_data:
